//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeechPathology.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeechPathology.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The European Commission support for the production of this mobile app does not constitute an endorsement of the contents which reflects the views only of the authors, and the Commission cannot be held responsible for any use which may be made of the information contained therein..
        /// </summary>
        public static string AboutFooter {
            get {
                return ResourceManager.GetString("AboutFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application was designed by the Erasmus+ KA2 Strategic Partnership Project consortium of “Interactive Tools for Teachers and Children at Initial Education”.
        /// </summary>
        public static string AboutIntro {
            get {
                return ResourceManager.GetString("AboutIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information please visit our website and social media channels..
        /// </summary>
        public static string AboutSocial {
            get {
                return ResourceManager.GetString("AboutSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the project.
        /// </summary>
        public static string AboutTheProject {
            get {
                return ResourceManager.GetString("AboutTheProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age at test date.
        /// </summary>
        public static string AgeAtTest {
            get {
                return ResourceManager.GetString("AgeAtTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Based Test.
        /// </summary>
        public static string AgeCalculator {
            get {
                return ResourceManager.GetString("AgeCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age of the Child.
        /// </summary>
        public static string AgeCalculatorTitle {
            get {
                return ResourceManager.GetString("AgeCalculatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not set an age to test, or the age you chose is too young. Please input a valid birth date..
        /// </summary>
        public static string AgeNotSetMsg {
            get {
                return ResourceManager.GetString("AgeNotSetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Not Testable.
        /// </summary>
        public static string AgeNotSetTitle {
            get {
                return ResourceManager.GetString("AgeNotSetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORTANT:
        ///If you suspect your child is in need of speech therapy, you should consult a speech therapist.
        ///This application does not replace a speech therapist, but offers an additional supporting tool..
        /// </summary>
        public static string ApplicationNotice {
            get {
                return ResourceManager.GetString("ApplicationNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articulation Test.
        /// </summary>
        public static string ArticulationTest {
            get {
                return ResourceManager.GetString("ArticulationTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blend.
        /// </summary>
        public static string Blend {
            get {
                return ResourceManager.GetString("Blend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blended.
        /// </summary>
        public static string Blended {
            get {
                return ResourceManager.GetString("Blended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string CorrectAbbreviation {
            get {
                return ResourceManager.GetString("CorrectAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test date.
        /// </summary>
        public static string DateOfTest {
            get {
                return ResourceManager.GetString("DateOfTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string DayPlural {
            get {
                return ResourceManager.GetString("DayPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string DaySingular {
            get {
                return ResourceManager.GetString("DaySingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        public static string Final {
            get {
                return ResourceManager.GetString("Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashcards.
        /// </summary>
        public static string Flashcards {
            get {
                return ResourceManager.GetString("Flashcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating PDF….
        /// </summary>
        public static string GeneratingPDF {
            get {
                return ResourceManager.GetString("GeneratingPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect.
        /// </summary>
        public static string Incorrect {
            get {
                return ResourceManager.GetString("Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial.
        /// </summary>
        public static string Initial {
            get {
                return ResourceManager.GetString("Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oral Language Skills.
        /// </summary>
        public static string LanguageSkills {
            get {
                return ResourceManager.GetString("LanguageSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Language Skills.
        /// </summary>
        public static string LanguageSkillsButton {
            get {
                return ResourceManager.GetString("LanguageSkillsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  correctly?.
        /// </summary>
        public static string LetterFocusPost {
            get {
                return ResourceManager.GetString("LetterFocusPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your child pronounce .
        /// </summary>
        public static string LetterFocusPre {
            get {
                return ResourceManager.GetString("LetterFocusPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters.
        /// </summary>
        public static string Letters {
            get {
                return ResourceManager.GetString("Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medial.
        /// </summary>
        public static string Medial {
            get {
                return ResourceManager.GetString("Medial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed.
        /// </summary>
        public static string Mixed {
            get {
                return ResourceManager.GetString("Mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string MonthPlural {
            get {
                return ResourceManager.GetString("MonthPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string MonthSingular {
            get {
                return ResourceManager.GetString("MonthSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NC.
        /// </summary>
        public static string NotCorrectAbbreviation {
            get {
                return ResourceManager.GetString("NotCorrectAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in browser.
        /// </summary>
        public static string OpenInBrowser {
            get {
                return ResourceManager.GetString("OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonological Test Results.
        /// </summary>
        public static string PhonologicalTestResults {
            get {
                return ResourceManager.GetString("PhonologicalTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position test results.
        /// </summary>
        public static string PositionTestResults {
            get {
                return ResourceManager.GetString("PositionTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Pathology Tools.
        /// </summary>
        public static string ProjectTitle {
            get {
                return ResourceManager.GetString("ProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Usage.
        /// </summary>
        public static string RecomendedUsage {
            get {
                return ResourceManager.GetString("RecomendedUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to resume your previous test?.
        /// </summary>
        public static string ResumeTestMessage {
            get {
                return ResourceManager.GetString("ResumeTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start afresh.
        /// </summary>
        public static string ResumeTestNo {
            get {
                return ResourceManager.GetString("ResumeTestNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending test found.
        /// </summary>
        public static string ResumeTestTitle {
            get {
                return ResourceManager.GetString("ResumeTestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume test.
        /// </summary>
        public static string ResumeTestYes {
            get {
                return ResourceManager.GetString("ResumeTestYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score: {0:0.0%}.
        /// </summary>
        public static string ScoreFmt {
            get {
                return ResourceManager.GetString("ScoreFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select excluded sound.
        /// </summary>
        public static string Selectexcludedsound {
            get {
                return ResourceManager.GetString("Selectexcludedsound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select sound.
        /// </summary>
        public static string Selectsound {
            get {
                return ResourceManager.GetString("Selectsound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select sound position.
        /// </summary>
        public static string SelectSoundPosition {
            get {
                return ResourceManager.GetString("SelectSoundPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select View.
        /// </summary>
        public static string SelectView {
            get {
                return ResourceManager.GetString("SelectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share language skills.
        /// </summary>
        public static string ShareLanguageSkills {
            get {
                return ResourceManager.GetString("ShareLanguageSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share results.
        /// </summary>
        public static string ShareResults {
            get {
                return ResourceManager.GetString("ShareResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share worksheet.
        /// </summary>
        public static string ShareWorksheet {
            get {
                return ResourceManager.GetString("ShareWorksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound test results.
        /// </summary>
        public static string SoundTestResults {
            get {
                return ResourceManager.GetString("SoundTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound test results.
        /// </summary>
        public static string SoundTestResultsButton {
            get {
                return ResourceManager.GetString("SoundTestResultsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Sound Development.
        /// </summary>
        public static string SpeechSounds {
            get {
                return ResourceManager.GetString("SpeechSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Test.
        /// </summary>
        public static string SpeechSoundsButton {
            get {
                return ResourceManager.GetString("SpeechSoundsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to the test.
        /// </summary>
        public static string SpeechSoundsDetail {
            get {
                return ResourceManager.GetString("SpeechSoundsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Sound Progress by Age.
        /// </summary>
        public static string SpeechSoundsSubtitle {
            get {
                return ResourceManager.GetString("SpeechSoundsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheets.
        /// </summary>
        public static string Worksheets {
            get {
                return ResourceManager.GetString("Worksheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheet saved..
        /// </summary>
        public static string WorksheetSaved {
            get {
                return ResourceManager.GetString("WorksheetSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheets view.
        /// </summary>
        public static string WorksheetsView {
            get {
                return ResourceManager.GetString("WorksheetsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string YearPlural {
            get {
                return ResourceManager.GetString("YearPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string YearSingular {
            get {
                return ResourceManager.GetString("YearSingular", resourceCulture);
            }
        }
    }
}
