//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeechPathology.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeechPathology.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The European Commission support for the production of this mobile app does not constitute an endorsement of the contents which reflects the views only of the authors, and the Commission cannot be held responsible for any use which may be made of the information contained therein..
        /// </summary>
        internal static string AboutFooter {
            get {
                return ResourceManager.GetString("AboutFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application was designed by the Erasmus+ KA2 Strategic Partnership Project consortium of “Interactive Tools for Teachers and Children at Initial Education”.
        /// </summary>
        internal static string AboutIntro {
            get {
                return ResourceManager.GetString("AboutIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information please visit our website and social media channels..
        /// </summary>
        internal static string AboutSocial {
            get {
                return ResourceManager.GetString("AboutSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the project.
        /// </summary>
        internal static string AboutTheProject {
            get {
                return ResourceManager.GetString("AboutTheProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Calculator.
        /// </summary>
        internal static string AgeCalculator {
            get {
                return ResourceManager.GetString("AgeCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORTANT:
        ///If you suspect your child is in need of speech therapy, you should consult a speech therapist.
        ///This application does not replace a speech therapist, but offers an additional supporting tool..
        /// </summary>
        internal static string ApplicationNotice {
            get {
                return ResourceManager.GetString("ApplicationNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articulation Test.
        /// </summary>
        internal static string ArticulationTest {
            get {
                return ResourceManager.GetString("ArticulationTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        internal static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        internal static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        internal static string Final {
            get {
                return ResourceManager.GetString("Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashcards.
        /// </summary>
        internal static string Flashcards {
            get {
                return ResourceManager.GetString("Flashcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating PDF ….
        /// </summary>
        internal static string GeneratingPDF {
            get {
                return ResourceManager.GetString("GeneratingPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect.
        /// </summary>
        internal static string Incorrect {
            get {
                return ResourceManager.GetString("Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial.
        /// </summary>
        internal static string Initial {
            get {
                return ResourceManager.GetString("Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medial.
        /// </summary>
        internal static string Medial {
            get {
                return ResourceManager.GetString("Medial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed.
        /// </summary>
        internal static string Mixed {
            get {
                return ResourceManager.GetString("Mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in browser.
        /// </summary>
        internal static string OpenInBrowser {
            get {
                return ResourceManager.GetString("OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonological Test Results.
        /// </summary>
        internal static string PhonologicalTestResults {
            get {
                return ResourceManager.GetString("PhonologicalTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position test results.
        /// </summary>
        internal static string PositionTestResults {
            get {
                return ResourceManager.GetString("PositionTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Usage.
        /// </summary>
        internal static string RecomendedUsage {
            get {
                return ResourceManager.GetString("RecomendedUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select excluded sound.
        /// </summary>
        internal static string Selectexcludedsound {
            get {
                return ResourceManager.GetString("Selectexcludedsound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select sound.
        /// </summary>
        internal static string Selectsound {
            get {
                return ResourceManager.GetString("Selectsound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select sound position.
        /// </summary>
        internal static string SelectSoundPosition {
            get {
                return ResourceManager.GetString("SelectSoundPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select View.
        /// </summary>
        internal static string SelectView {
            get {
                return ResourceManager.GetString("SelectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share results.
        /// </summary>
        internal static string ShareResults {
            get {
                return ResourceManager.GetString("ShareResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share worksheet.
        /// </summary>
        internal static string ShareWorksheet {
            get {
                return ResourceManager.GetString("ShareWorksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound test results.
        /// </summary>
        internal static string SoundTestResults {
            get {
                return ResourceManager.GetString("SoundTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheets.
        /// </summary>
        internal static string Worksheets {
            get {
                return ResourceManager.GetString("Worksheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheet saved..
        /// </summary>
        internal static string WorksheetSaved {
            get {
                return ResourceManager.GetString("WorksheetSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheets view.
        /// </summary>
        internal static string WorksheetsView {
            get {
                return ResourceManager.GetString("WorksheetsView", resourceCulture);
            }
        }
    }
}
